# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:  
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test
      run: mvn test
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
